### ISSUE TITLE
Admin can log in to Farmer Dashboard

### ISSUE THREAD

**Issue by jay1-53** [radical-doubting/anikultura-frontend#14]
### Description

Any admin account can be logged in to the farmer dashboard, run through the tutorial, but will encounter a server error upon finishing it and re-directing the account to dashboard.

### Reproduction steps

1. Log in an admin account on a farmer dashboard
2. Proceed through the tutorial until the last slide
3. Click 'Handa Na!'

### Expected behavior

The admin can not log in through the farmer dashboard.

**Comment by jg-rivera** [comment]
The back-end should catch this and prevent this from happening.
