### ISSUE TITLE
Farmer can submit reports without allocated seeds

### ISSUE THREAD

**Issue by jg-rivera** [radical-doubting/anikultura-frontend#16]
### Description

Farmer can submit reports without allocated seeds. This causes the crop dropdown to be blank when a farmer tries to submit a report.

### Reproduction steps

1. Log in to a farmer without allocated seeds.
2. Click the submit a report button.
3. Observe that the crop dropdown is blank.

### Expected behavior

A farmer should be stopped early on from submitting a report when he or she does not actually have any allocated seeds from his or her batch.

### Affected browsers (if applicable)

Firefox, Chrome, Safari, Microsoft Edge

**Comment by gpassport** [comment]
After testing, the **farmer is stopped from proceeding** and is **prompted with an error message** if they do not have any allocated seeds when submitting a report. The **error message** is currently in Filipino, and is **still not translated**  when setting into different languages, will need to update that.
