### ISSUE TITLE
Translation raw script on Farmer Dashboard

### ISSUE THREAD

**Issue by jay1-53** [radical-doubting/anikultura-frontend#24]
### Description

The raw script of translation appears on the farmer dashboard.

### Prerequisite:

1. The user must be a registered farmer
2. The farmer must be included in a farmland
3. and has allocated seeds

### Steps

1. The farmer will go to the website application and log in
2. The farmer proceeds to another stage by pressing the submit button 
3. The dashboard will refresh, images and titles will refresh, but the script will displayed as raw.

![image](https://user-images.githubusercontent.com/27613092/196119549-4d534106-499b-4363-92f5-b826fd78e306.png)

### Expected behavior

The dashboard will be filled up with raw translation script.

### Relevant log output

```shell
No response
```

### Affected browsers (if applicable)

Firefox, Chrome, Safari, Microsoft Edge

**Comment by jg-rivera** [comment]
See this [discussion](https://stackoverflow.com/questions/68541240/translation-working-but-only-after-page-resresh) for an idea of the fix.
